**Vectorization:** It is a technique in data processing , used in NumPy, in which operations are directly applied to the whole array or dataset at once, without traversing and processing each element using loops one by one.

*For Example,* in numpy_task.py we scaled by doubling all the values of the matrix without using a loop.
*i.e. processed_data = data_points * 2*  
Here, data_points is reshaped into a 2X2 matrix, and the operation is applied to all the elements at once.


NumPy is used here as the reshaped matrix allows the model to process the given data in parallel,thus makes the overall computations faster and more efficient

**DataFrame:** It is a powerful data structure that organises the data in a tabular form consiting of rows and columns.

In this task, I used a data.csv file whose data is read using *df = pd.read_csv("AI-ML\datasets\data.csv")* command , this converts the csv data into DataFrame for easy processing.

# Day 4: Pre-processing Techniques

In [1]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [21, np.nan, 23, 24],
    'Score': [80, 75, np.nan, 95]
}

df = pd.DataFrame(data)
df

      Name   Age  Score
0    Alice  21.0   80.0
1      Bob   NaN   75.0
2  Charlie  23.0    NaN
3    David  24.0   95.0

In [ ]:
# Dropping a row
df_dropped = df.dropna()
df_dropped

    Name   Age  Score
0  Alice  21.0   80.0
3  David  24.0   95.0

In [ ]:
#Filing a row
df_filled = df.copy()

df_filled['Age'] = df_filled['Age'].fillna(df_filled['Age'].mean())
df_filled['Score'] = df_filled['Score'].fillna(0)

df_filled

      Name        Age  Score
0    Alice  21.000000   80.0
1      Bob  22.666667   75.0
2  Charlie  23.000000    0.0
3    David  24.000000   95.0

### Comparison:

- Dropping data removes incomplete rows but reduces dataset size.
- Filling data keeps all records and maintains dataset size.
- Imputation is preferred when data is limited.

### 2AZWhy is it better to fill a missing age with the mean rather than just putting 0?
If we replace missing age with 0, it will be impossible since age cannot be zero.
This will introduce erroneous information to our analysis.

If we replace missing age with the mean value, it will give us a sensible replacement.
We can maintain the structure of our data.

Thus, using the mean for filling missing age is preferable over using 0.